ALTER TABLE roles DROP CONSTRAINT roles_name_check;

ALTER TABLE roles ADD CONSTRAINT roles_name_check
    CHECK (name IN ('ROLE_BUYER', 'ROLE_SELLER', 'ROLE_ADMIN', 'ROLE_DISTRIBUTION_POINT_EMPLOYEE', 'ROLE_DELIVERY'));


INSERT INTO roles (name) VALUES ('ROLE_DELIVERY');
