spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DB}?authSource=admin

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVER}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
