server:
  port: 8085

spring:
  application:
    name: review-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.feryafox.kafka.deserializer.CustomKafkaDeserializer
      properties:
        spring.json.trusted.packages: "*"
        event.class.ProductEvent: ru.feryafox.kafka.models.ProductEvent
      group-id: review-service-group

jwt:
  secret: ${JWT_SECRET}

internal:
  api:
    key: ${INTERNAL_SECRET_KEY}

springdoc:
  api-docs:
    enabled: true
    path: /review/v3/api-docs
  swagger-ui:
    enabled: false
    path: /review/swagger-ui.html
