CREATE TABLE orders
(
    order_id     UUID                        NOT NULL,
    user_id      UUID                        NOT NULL,
    order_status VARCHAR(255)                NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    total_price  DECIMAL                     NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

CREATE TABLE product_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id VARCHAR(255)                            NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    shop_id    UUID                                    NOT NULL,
    price      DECIMAL                                 NOT NULL,
    order_id   UUID                                    NOT NULL,
    CONSTRAINT pk_product_items PRIMARY KEY (id)
);

ALTER TABLE product_items
    ADD CONSTRAINT FK_PRODUCT_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (order_id);