server:
  port: 8084

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://10.242.56.8:5431/yet_another_e_shop_product
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://root:example@10.242.56.8:27017/yet_another_e_shop_product?authSource=admin

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    show-sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.feryafox.kafka.deserializer.CustomKafkaDeserializer
      properties:
        spring.json.trusted.packages: "*"
        event.class.ShopEvent: ru.feryafox.kafka.models.ShopEvent
      group-id: product-service-group

    bootstrap-servers: "10.242.56.8:9092"

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG

jwt:
  secret: ${JWT_SECRET}
