spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DB}?authSource=admin

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVER}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

minio:
  url: http://${MINIO_HOST}
  access-key: ${MINIO_NAME}
  secret-key: ${MINIO_PASSWORD}
  bucket: product-images
