server:
  port: 8081


spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://10.242.56.8:5431/yet_another_e_shop_auth
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: "10.242.56.8:9092"

  jpa:
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  jwt-expiration-ms: 3600000
  refresh-token-expiration-ms: 86400000
  max-session: 5

springdoc:
  api-docs:
    enabled: true
    path: /auth/v3/api-docs
  swagger-ui:
    enabled: false
    path: /auth/swagger-ui.html