server:
  port: 8081


spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://10.242.56.8:5431/yet_another_e_shop_auth
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  jwt-expiration-ms: 3600000
  refresh-token-expiration-ms: 86400000
  max-session: 5

