server:
  port: 8081

spring:
  application:
    name: auth-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  jwt-expiration-ms: 3600000
  refresh-token-expiration-ms: 86400000
  max-session: 5

springdoc:
  api-docs:
    enabled: true
    path: /auth/v3/api-docs
  swagger-ui:
    enabled: false
    path: /auth/swagger-ui.html