server:
  port: 8088

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://10.242.56.8:5431/yet_another_e_shop_notification
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.feryafox.kafka.deserializer.CustomKafkaDeserializer
      properties:
        spring.json.trusted.packages: "*"
        event.class.UserEvent: ru.feryafox.kafka.models.UserEvent
        event.class.NotificationEvent: ru.feryafox.kafka.models.NotificationEvent
      group-id: notification-service-group

    bootstrap-servers: "10.242.56.8:9092"

jwt:
  secret: ${JWT_SECRET}
