server:
  port: 8087

spring:
  application:
    name: order-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    show-sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.feryafox.kafka.deserializer.CustomKafkaDeserializer
      properties:
        event.class.OrderEvent: ru.feryafox.kafka.models.OrderEvent
        event.class.PaymentResponseEvent: ru.feryafox.kafka.models.PaymentResponseEvent
        spring.json.trusted.packages: "*"
      group-id: order-service-group

jwt:
  secret: ${JWT_SECRET}

springdoc:
  api-docs:
    enabled: true
    path: /order/v3/api-docs
  swagger-ui:
    enabled: false
    path: /order/swagger-ui.html
