server:
  port: 8080

spring:
  application:
    name: GatewayService

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    ru.feryafox.gatewayservice.filters.RouteLoggingFilter: DEBUG  # Укажите правильный путь к вашему классу
