server:
  port: 8080

spring:
  application:
    name: GatewayService

  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/auth/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/