server:
  port: 8080
  max-http-request-header-size: 32KB

spring:
  application:
    name: GatewayService

  cloud:
    gateway:
      routes:
        - id: auth-service-auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: auth-service-profile
          uri: lb://auth-service
          predicates:
            - Path=/profile/**

        - id: admin-auth-service
          uri: lb://auth-service
          predicates:
            - Path=/admin/auth/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

        - id: internal-product-service
          uri: lb://product-service
          predicates:
            - Path=/internal/product/**
          filters:
            - name: InternalFilter

        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/shop/**

        - id: internal-shop-service
          uri: lb://shop-service
          predicates:
            - Path=/internal/shop/**
          filters:
            - name: InternalFilter

        - id: internal-auth-service
          uri: lb://auth-service
          predicates:
            - Path=/internal/auth/**
          filters:
            - name: InternalFilter

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**

        - id: internal-cart-service
          uri: lb://cart-service
          predicates:
            - Path=/internal/cart/**
          filters:
            - name: InternalFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: internal-order-service
          uri: lb://order-service
          predicates:
            - Path=/internal/order/**
          filters:
            - name: InternalFilter

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    ru.feryafox.gatewayservice.filters.RouteLoggingFilter: DEBUG  # Укажите правильный путь к вашему классу

internal:
  api:
    key: ${INTERNAL_SECRET_KEY}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs

      - name: auth-service
        url: /auth/v3/api-docs

      - name: cart-service
        url: /cart/v3/api-docs

      - name: order-service
        url: /order/v3/api-docs

      - name: payment-service
        url: /payment/v3/api-docs

      - name: product-service
        url: /product/v3/api-docs

      - name: review-service
        url: /review/v3/api-docs

      - name: shop-service
        url: /shop/v3/api-docs
