server:
  port: 8080

spring:
  application:
    name: GatewayService

  cloud:
    gateway:
      routes:
        - id: auth-service-auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: auth-service-profile
          uri: lb://auth-service
          predicates:
            - Path=/profile/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

        - id: shop-service
          uri: lb://shop-service
          predicates:
            - Path=/shop/**

        - id: internal-shop-service
          uri: lb://shop-service
          predicates:
            - Path=/internal/shop/**
          filters:
            - name: InternalFilter

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    ru.feryafox.gatewayservice.filters.RouteLoggingFilter: DEBUG  # Укажите правильный путь к вашему классу

internal:
  api:
    key: ${INTERNAL_SECRET_KEY}